name: "Test server"
description: "Test the currently running medusa server to see if a user has been created and that the server is seeded"

inputs:
  email:
    description: "email of user to log in"
    required: false
    default: "test@test.com"
  password:
    description: "password of user to log in"
    required: false
    default: "password"
  pathToSeedData:
    description: "path to seed data"
    required: false
    default: "../cli-test/data/seed.json"

runs:
  using: "composite"
  steps:
    - name: Wait for live server response
      shell: "bash"
      run: ./integration-tests/scripts/cli/wait-for-server-live.sh
      # run: ./node_modules/@medusajs/medusa-cli/scripts/__tests__/wait-for-server-live.sh

      #'curl -X POST http://localhost:9000/admin/auth -H "Content-Type: application/json" -d ''{"email":"test@test.com", "password":"password"}'''
    - name: Log in with user
      shell: "bash"
      run: ./integration-tests/scripts/cli/login.sh ${{ inputs.email }} ${{ inputs.password }}
      # run: ./node_modules/@medusajs/medusa-cli/scripts/__tests__/login.sh ${{ inputs.email }} ${{ inputs.password }}

      # "curl -X GET http://localhost:9000/store/products"
    - name: GetProducts
      shell: "bash"
      run: ./integration-tests/scripts/cli/get-products.sh ${{ inputs.pathToSeedData }}
      # run: ./node_modules/@medusajs/medusa-cli/scripts/__tests__/get-products.sh ${{ inputs.pathToSeedData }}

    - name: Kill server
      shell: "bash"
      run: kill -9 $(lsof -t -i :9000)
