get:
  operationId: GetProductsTypes
  summary: List Product Types
  description: Retrieves a list of Product Types.
  x-authenticated: true
  x-codeSamples:
    - lang: JavaScript
      label: JS Client
      source:
        $ref: ../code_samples/JavaScript/products_types/getundefined
    - lang: Shell
      label: cURL
      source:
        $ref: ../code_samples/Shell/products_types/getundefined
  security:
    - api_token: []
    - cookie_auth: []
  tags:
    - Product
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            properties:
              types:
                type: array
                items:
                  $ref: ../components/schemas/product_type.yaml
