get:
  operationId: GetProductsTagUsage
  summary: List Product Tags Usage Number
  description: Retrieves a list of Product Tags with how many times each is used.
  x-authenticated: true
  x-codeSamples:
    - lang: JavaScript
      label: JS Client
      source:
        $ref: ../code_samples/JavaScript/products_tag-usage/getundefined
    - lang: Shell
      label: cURL
      source:
        $ref: ../code_samples/Shell/products_tag-usage/getundefined
  security:
    - api_token: []
    - cookie_auth: []
  tags:
    - Product Tag
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            properties:
              tags:
                type: array
                items:
                  properties:
                    id:
                      description: The ID of the tag.
                      type: string
                    usage_count:
                      description: The number of products that use this tag.
                      type: string
                    value:
                      description: The value of the tag.
                      type: string
