name: Publish canary
on: 
  pull_request:
    branches:
      - develop

jobs:
  publish-canary:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.5
        with:
          fetch-depth: 0

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1
        with:
          node-version: "14"
          cache: "yarn"
          registry-url: 'https://registry.npmjs.org'
      - name: "Get Branch Name"
        run: |
          BRANCH_NAME="${GITHUB_HEAD_REF}"
          echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV
      - name: Format Version Name
        run: |
          VERSION_NAME=`echo ${{ env.BRANCH_NAME }} | sed "s/[/_]/-/g"`
          echo "VERSION_NAME=${VERSION_NAME}" >> $GITHUB_ENV 
      - name: Publish Canary
        run: lerna publish --yes --canary --preid ${{ env.VERSION_NAME }} --force-publish="*"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}