on:
  workflow_call:
    inputs:
      email:
        type: string
        description: "email of user to log in"
        required: false
        default: "test@test.com"
      password:
        type: string
        description: "password of user to log in"
        required: false
        default: "password"
      pathToSeedData:
        type: string
        description: "path to seed data"
        required: false
        default: "../cli-test/data/seed.json"
      workingDirectory:
        type: string
        description: "working directory"
        required: false
        default: "."

jobs:
  test-server:
    name: "Test local medusa instance"
    runs-on: ubuntu-latest
    steps:
      - name: Wait for live server response
        working-directory: ${{ inputs.workingDirectory }}
        run: ./node_modules/@medusajs/medusa-cli/scripts/__tests__/wait-for-server-live.sh

        #'curl -X POST http://localhost:9000/admin/auth -H "Content-Type: application/json" -d ''{"email":"test@test.com", "password":"password"}'''
      - name: Log in with user
        working-directory: ${{ inputs.workingDirectory }}
        run: ./node_modules/@medusajs/medusa-cli/scripts/__tests__/login.sh ${{ inputs.email }} ${{ inputs.password }}

        # "curl -X GET http://localhost:9000/store/products"
      - name: GetProducts
        working-directory: ${{ inputs.workingDirectory }}
        run: ./node_modules/@medusajs/medusa-cli/scripts/__tests__/get-products.sh ${{ inputs.pathToSeedData }}

      - name: Kill server
        run: kill -9 $(lsof -t -i :9000)
